### ISSUE TITLE
ERROR in ./app/index.js - Symbol is not defined

### ISSUE THREAD

**Issue by james-yin** [martijnboland/VSReact#4]
After I cloned the whole project and pressed F5 in VS2015. I'm getting the following error in the Task Runner Explorer:

```
ERROR in ./app/index.js
Module build failed: ReferenceError: Symbol is not defined
    at plugin (C:\dev\VSReact\VSReact.Web\node_modules\react-hot-loader\lib\babel\index.js:53:23)
    at Function.memoisePluginContainer (C:\dev\VSReact\VSReact.Web\node_modules\babel-core\lib\transformation\file\options\option-manager.js:134:13)
    at Function.normalisePlugin (C:\dev\VSReact\VSReact.Web\node_modules\babel-core\lib\transformation\file\options\option-manager.js:168:32)
    at C:\dev\VSReact\VSReact.Web\node_modules\babel-core\lib\transformation\file\options\option-manager.js:208:30
    at Array.map (native)
    at Function.normalisePlugins (C:\dev\VSReact\VSReact.Web\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:20)
    at OptionManager.mergeOptions (C:\dev\VSReact\VSReact.Web\node_modules\babel-core\lib\transformation\file\options\option-manager.js:300:36)
    at OptionManager.addConfig (C:\dev\VSReact\VSReact.Web\node_modules\babel-core\lib\transformation\file\options\option-manager.js:232:10)
    at OptionManager.findConfigs (C:\dev\VSReact\VSReact.Web\node_modules\babel-core\lib\transformation\file\options\option-manager.js:436:16)
    at OptionManager.init (C:\dev\VSReact\VSReact.Web\node_modules\babel-core\lib\transformation\file\options\option-manager.js:484:12)
    at File.initOptions (C:\dev\VSReact\VSReact.Web\node_modules\babel-core\lib\transformation\file\index.js:223:65)
    at new File (C:\dev\VSReact\VSReact.Web\node_modules\babel-core\lib\transformation\file\index.js:140:24)
    at Pipeline.transform (C:\dev\VSReact\VSReact.Web\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\dev\VSReact\VSReact.Web\node_modules\babel-loader\index.js:14:22)
    at Object.module.exports (C:\dev\VSReact\VSReact.Web\node_modules\babel-loader\index.js:88:12)
```

I do have NodeJS v4 and Webpack Task Runner Extension installed. I also did

```
npm install babel-core --save-dev
```

locally to my VSReact project folder. What else am I doing wrong? Or are the new release packages breaking this wonderful build?

thanks!

**Comment by yaronlevi** [comment]
Also happend to me

**Comment by jmaocanada** [comment]
Same here

**Comment by wordythebyrd** [comment]
I have not resolved this issue yet, but it looks like an issue using the latest version of html-webpack-plugin. 

[Migrating from 1.x to 2.x](https://github.com/ampedandwired/html-webpack-plugin/blob/master/migration.md)

**Comment by naderelfaky** [comment]
Same issue here

**Comment by pastorsj** [comment]
Same here

**Comment by ghooton** [comment]
Has anyone had any luck with this yet? Same issue here

**Comment by sahilkhan99** [comment]
Same issue , but below answer from stackoverflow resolved it. Have to update External web tools -> path settings.

http://stackoverflow.com/questions/35889975/gulp-task-failing-when-run-from-vs-2015-task-runner-explorer-but-not-from-comma

**Comment by martijnboland** [comment]
Just updated all libs to the latest version. There was an issue with the HtmlWebpackPlugin that is solved now. If problems still persist, try the suggestion from the link above to let Visual Studio use the node.js version from the path and not its own old version (see also https://blogs.msdn.microsoft.com/webdev/2015/03/19/customize-external-web-tools-in-visual-studio-2015/).

**Comment by Beatusvir** [comment]
I just cloned this repo and only updated typescript version since VS warned me about it (just a project setting) and runs perfectly.
I'm running VS 2017 Community, fully updated and installed Webpack Task Runner like 2 hours before posting. So try to update everything and try again.

**Comment by martijnboland** [comment]
Thanks for the heads up.
